# Generated by Django 3.0.4 on 2020-03-14 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PetInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pet_name', models.CharField(max_length=100)),
                ('pet_breed', models.CharField(max_length=100)),
                ('pet_age', models.IntegerField()),
                ('pet_weight', models.IntegerField()),
                ('uni_pk', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'PetInfo',
            },
        ),
        migrations.CreateModel(
            name='PetSymptom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('symptom_type', models.CharField(max_length=100)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.PetInfo')),
            ],
            options={
                'db_table': 'PetSymptom',
            },
        ),
        migrations.CreateModel(
            name='EmailFromVisitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('v_email', models.EmailField(max_length=100)),
                ('v_subject', models.TextField()),
                ('v_user_name', models.CharField(max_length=50)),
                ('v_message', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.PetInfo')),
            ],
            options={
                'db_table': 'EmailFromVisitor',
            },
        ),
    ]
