# Generated by Django 3.0.4 on 2020-03-16 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200316_0019'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_name', models.CharField(max_length=100)),
                ('solution_name', models.CharField(max_length=100)),
                ('product_image', models.ImageField(upload_to='')),
            ],
            options={
                'db_table': 'Product',
            },
        ),
    ]
